/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("net.java.dev.jna:jna:5.14.0")
    api("com.github.jnr:jnr-ffi:2.2.16")
    api("org.apache.logging.log4j:log4j-core:2.22.1")
    api("org.apache.logging.log4j:log4j-api:2.22.1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.2")
    testImplementation("com.nimbusds:nimbus-jose-jwt:9.37.3")
}

group = "com.isblocks.pkcs11"
version = "1.0"
description = "isblocks-java-pkcs11"
java.sourceCompatibility = JavaVersion.VERSION_21

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
